//! \file kerneltest/kerneltest.hpp The master *latest version* KernelTest include file. All KernelTest consuming libraries should include this header only.
#include "version.hpp"

#if defined(_MSC_VER) && !defined(__clang__)
#define BOOST_KERNELTEST_HEADERS_PATH2 BOOST_KERNELTEST_VERSION_GLUE(v, BOOST_KERNELTEST_HEADERS_VERSION, /kerneltest.hpp)
#else
#define BOOST_KERNELTEST_HEADERS_PATH2 BOOST_KERNELTEST_VERSION_GLUE(v, BOOST_KERNELTEST_HEADERS_VERSION,)/kerneltest.hpp
#endif

#if 0 // cmake's Makefiles and Ninja generators won't pick up dependent headers without this
#include "v1.0/kerneltest.hpp"
#endif

#define BOOST_KERNELTEST_HEADERS_PATH4(a) #a
#define BOOST_KERNELTEST_HEADERS_PATH3(a) BOOST_KERNELTEST_HEADERS_PATH4(a)
//! \brief The KernelTest headers path generated by the preprocessor from the version
#define BOOST_KERNELTEST_HEADERS_PATH BOOST_KERNELTEST_HEADERS_PATH3(BOOST_KERNELTEST_HEADERS_PATH2)
#include BOOST_KERNELTEST_HEADERS_PATH
#undef BOOST_KERNELTEST_HEADERS_PATH
#undef BOOST_KERNELTEST_HEADERS_PATH2
#undef BOOST_KERNELTEST_HEADERS_PATH3
#undef BOOST_KERNELTEST_HEADERS_PATH4
