# DO NOT EDIT, GENERATED BY SCRIPT
set(kerneltest_HEADERS
  "include/kerneltest.hpp"
  "include/kerneltest/kerneltest.hpp"
  "include/kerneltest/revision.hpp"
  "include/kerneltest/v1.0/child_process.hpp"
  "include/kerneltest/v1.0/config.hpp"
  "include/kerneltest/v1.0/hooks/custom.hpp"
  "include/kerneltest/v1.0/hooks/filesystem_workspace.hpp"
  "include/kerneltest/v1.0/kerneltest.hpp"
  "include/kerneltest/v1.0/permute_parameters.hpp"
  "include/kerneltest/v1.0/test_kernel.hpp"
  "include/kerneltest/version.hpp"
  "include/kerneltest/v1.0/detail/impl/child_process.ipp"
  "include/kerneltest/v1.0/detail/impl/posix/child_process.ipp"
  "include/kerneltest/v1.0/detail/impl/windows/child_process.ipp"
)
