# DO NOT EDIT, GENERATED BY SCRIPT
set(kerneltest_TESTS
  "test/auto_permute_test_kernel1.hpp"
  "test/auto_permute_test_kernel2.hpp"
  "test/coverage_main.cpp"
)
# DO NOT EDIT, GENERATED BY SCRIPT
set(kerneltest_COMPILE_TESTS
)
# DO NOT EDIT, GENERATED BY SCRIPT
set(kerneltest_COMPILE_FAIL_TESTS
)
